config/routes.rb
Rails.application.routes.draw do
    # require 'sidekiq/web'
  require 'admin_constraint'
  # mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new
  mount Ckeditor::Engine => '/ckeditor', constraints: AdminConstraint.new

  devise_scope :user do
    get "/users/sign_up",  :to => "devise/sessions#new"
  end  
  
  devise_for :users

  devise_scope :user do 
    get "/admin" => "devise/sessions#new" 
  end

  root 'home#index'

  # match '/about'                =>        'home#about',                 via: [:get],            :as => 'about'
  match '/careers'              =>        'home#careers',               via: [:get],            :as => 'careers'
  match '/purpose'              =>        'home#purpose',               via: [:get],            :as => 'purpose'
  match '/history'              =>        'home#history',               via: [:get],            :as => 'history'
  match '/why-choose-us'        =>        'home#why_choose_us',         via: [:get],            :as => 'why_choose_us'
  match '/contact'              =>        'home#contact',               via: [:get],            :as => 'contact'
  match '/privacy-policy'       =>        'home#privacy_policy',        via: [:get],            :as => 'privacy_policy'
  match '/locations/all-locations'          =>        'locations#all_locations',           via: [:get],            :as => 'all_locations'

  #########################################
  #==profiles
  #########################################
    get "/team", to: "profiles#index", as: :profiles
    post "/profiles", to: "profiles#create"
    get "/profiles/new", to: "profiles#new", as: :new_profile
    get "profiles/:id/edit", to: "profiles#edit", as: "edit_profile"
    patch "profiles/:id", to: "profiles#update"
    put "profiles/:id", to: "profiles#update"
    delete "profiles/:id", to: "profiles#destroy"

  #########################################
  #==locations url for location model
  #########################################
    get '/locations', to: 'locations#index', as: :locations
    post 'locations', to: 'locations#create'
    get '/locations/new', to: 'locations#new', as: :new_location
    get 'locations/:title_for_slug/edit', to: 'locations#edit', as: 'edit_location'
    get 'locations/:title_for_slug', to: 'locations#show', as: 'location'
    patch 'locations/:title_for_slug', to: 'locations#update'
    put 'locations/:title_for_slug', to: 'locations#update'
    delete 'locations/:title_for_slug', to: 'locations#destroy'

  #########################################
  #==press url for blog model
  #########################################
    get '/news', to: 'blogs#index', as: :blogs
    post 'news', to: 'blogs#create'
    get '/news/new', to: 'blogs#new', as: :new_blog
    get 'news/:title_for_slug/edit', to: 'blogs#edit', as: 'edit_blog'
    get 'news/:title_for_slug', to: 'blogs#show', as: 'blog'
    patch 'news/:title_for_slug', to: 'blogs#update'
    put 'news/:title_for_slug', to: 'blogs#update'
    delete 'news/:title_for_slug', to: 'blogs#destroy'

  #########################################
  #==press url for blog model
  #########################################
    get '/press', to: 'bligs#index', as: :bligs
    post 'press', to: 'bligs#create'
    get '/press/new', to: 'bligs#new', as: :new_blig
    get 'press/:title_for_slug/edit', to: 'bligs#edit', as: 'edit_blig'
    get 'press/:title_for_slug', to: 'bligs#show', as: 'blig'
    patch 'press/:title_for_slug', to: 'bligs#update'
    put 'press/:title_for_slug', to: 'bligs#update'
    delete 'press/:title_for_slug', to: 'bligs#destroy'

  match "/contacts"              =>        "contacts#create",              via: [:post]
  match "/applicants"            =>        "applicants#create",            via: [:post]
  
  get '/sitemap.xml', to: redirect("https://s3-us-west-2.amazonaws.com/gcg-group/sitemaps/sitemap.xml.gz", status: 301)

  match "*path", to: "home#catch_all", via: :all
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one :image, as: :imageable, :class_name => "Profile::Asset", dependent: :destroy
  accepts_nested_attributes_for :image, update_only: true
end

app/models/profile/asset.rb
class Profile::Asset < Image
  
  ##============================================================##
  ## Paperclip Interpolates
  ##============================================================##
  Paperclip.interpolates :imageable_type do |attachment, style|
    attachment.instance.imageable_type.downcase
  end

  Paperclip.interpolates :imageable_id do |attachment, style|
    attachment.instance.imageable_id
  end

  has_attached_file :pic,
    :path => "#{Rails.env}/:imageable_type/:imageable_id/:style/:filename",
    :styles => { 
      :square => ["300x300#", :jpg]
    },
    default_url: "//s3.amazonaws.com/gcg-ground/general/no-profile-image.png",
    :convert_options => {
     # :medium => "-quality 80 -interlace Plane",
     # :small => "-quality 80 -interlace Plane",
     # :thumb => "-quality 80 -interlace Plane",
     # :facebook_meta_tag => "-quality 80 -interlace Plane" 
    },
    :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }



  validates_attachment :pic, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }, size: { in: 0..3000.kilobytes }, presence: true

end


#needed default_url here because in the new action the build method semi-creates an image, and needs a default image otherwise it would say missing

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @profiles = Profile.order(position: :asc)
  end

  def new
    @profile = Profile.new
    @profile.build_image
  end
 
  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to profiles_path, notice: 'Profile was successfully created.'
    else
      render :new
    end
  end

  def update
    if @profile.update(profile_params)
      redirect_to profiles_path(@profile), notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @profile.destroy
    redirect_to profiles_url, notice: 'profile was successfully destroyed.'
  end

  private

    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:full_name, :title, :telephone, :mobile, :email, :position, image_attributes: [:id, :pic, :name])
    end
end

app/views/profiles/_form.html.erb
<%= form_for(@profile, :url => (@profile.new_record? ? "/profiles" : "/profiles/#{@profile.id}"), :html => { :multipart => true }) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :full_name %>
    <%= f.text_field :full_name, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :telephone %>
    <%= f.text_field :telephone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :mobile %>
    <%= f.text_field :mobile, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :position %>
    <%= f.number_field :position, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.fields_for :image do |t| %>
      <%= t.label :pic, "Main Image (for best results upload square photo)" %> <br>

      <% if @profile.image.present? %>
        <%= image_tag @profile.image.pic.url(:square), id: 'square_image', class: 'mb15' %><br/>
      <% else %>
        <img id="square_image" class="mb5" src="#" alt="">
      <% end %>
      <% if current_page?('/profiles/new') %>
        <%= t.file_field :pic, class: "form-control", style: "padding: 4px;", required: true %>  
      <% else %>
        <%= t.file_field :pic, class: "form-control", style: "padding: 4px;" %>
      <% end %>

    <% end %>
  </div>

  <div class="form-group">
    <%= f.submit class: "form-control btn btn-primary" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4 col-lg-offset-4">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/profiles/index.html.erb
<div class="container">
    <h5 class="mt30 mb60 text-center color-secondary">The Team <%= link_to "(Add new member)", new_profile_path if current_user.try(:admin?)%></h5>
    <% @profiles.each do |profile| %>
        <div class="col-sm-4 text-center mb30 mobile50">
          <%= image_tag(profile.image.pic.url(:square), class: "img-circle img-responsive imgTeam center-block") if profile.image.present? %>
          <h6><%= profile.full_name %></h6>
          <p style="color: #888; line-height: 28px; font-weight: normal; font-size: 14px;">
            <%= profile.title %> 
          </p>
          <% if profile.telephone.present? %>
            <p style="color: #888; line-height: 28px; font-weight: normal; font-size: 14px;""><%= "Tel. #{profile.telephone}" %></p> 
          <% else %>
            <p style="color: #888; line-height: 28px; font-weight: normal; font-size: 14px; visibility: hidden;"><%= "Tel. #{profile.telephone}"%></p>
          <% end %>
          <% if current_user.try(:admin?) %>
            <div>Position: <%= profile.position %></div> <br>
            <div><%= link_to 'Edit', edit_profile_path(profile), class:"btn btn-default btnBlog" if current_user.try(:admin?) %></div> <br>
            <div><%= link_to 'Destroy', "/profiles/#{profile.id}", class:"btn btn-default btnBlog", method: :delete, data: { confirm: 'Are you sure?' } if current_user.try(:admin?)%></div>
          <% end %>
        </div>
    <% end if @profiles.present?%>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4 col-lg-offset-4">
      <%= render 'form' %>
    </div>
  </div>
</div>