config/routes.rb
Rails.application.routes.draw do
    # require 'sidekiq/web'
  require 'admin_constraint'
  # mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new
  mount Ckeditor::Engine => '/ckeditor', constraints: AdminConstraint.new

  devise_scope :user do
    get "/users/sign_up",  :to => "devise/sessions#new"
  end  
  
  devise_for :users

  devise_scope :user do 
    get "/admin" => "devise/sessions#new" 
  end

  root 'home#index'

  # match '/about'                =>        'home#about',                 via: [:get],            :as => 'about'
  match '/careers'              =>        'home#careers',               via: [:get],            :as => 'careers'
  match '/purpose'              =>        'home#purpose',               via: [:get],            :as => 'purpose'
  match '/history'              =>        'home#history',               via: [:get],            :as => 'history'
  match '/why-choose-us'        =>        'home#why_choose_us',         via: [:get],            :as => 'why_choose_us'
  match '/contact'              =>        'home#contact',               via: [:get],            :as => 'contact'
  match '/privacy-policy'       =>        'home#privacy_policy',        via: [:get],            :as => 'privacy_policy'
  match '/locations/all-locations'          =>        'locations#all_locations',           via: [:get],            :as => 'all_locations'

  #########################################
  #==profiles
  #########################################
    get "/team", to: "profiles#index", as: :profiles
    post "/profiles", to: "profiles#create"
    get "/profiles/new", to: "profiles#new", as: :new_profile
    get "profiles/:id/edit", to: "profiles#edit", as: "edit_profile"
    patch "profiles/:id", to: "profiles#update"
    put "profiles/:id", to: "profiles#update"
    delete "profiles/:id", to: "profiles#destroy"

  #########################################
  #==locations url for location model
  #########################################
    get '/locations', to: 'locations#index', as: :locations
    post 'locations', to: 'locations#create'
    get '/locations/new', to: 'locations#new', as: :new_location
    get 'locations/:title_for_slug/edit', to: 'locations#edit', as: 'edit_location'
    get 'locations/:title_for_slug', to: 'locations#show', as: 'location'
    patch 'locations/:title_for_slug', to: 'locations#update'
    put 'locations/:title_for_slug', to: 'locations#update'
    delete 'locations/:title_for_slug', to: 'locations#destroy'

  #########################################
  #==press url for blog model
  #########################################
    get '/news', to: 'blogs#index', as: :blogs
    post 'news', to: 'blogs#create'
    get '/news/new', to: 'blogs#new', as: :new_blog
    get 'news/:title_for_slug/edit', to: 'blogs#edit', as: 'edit_blog'
    get 'news/:title_for_slug', to: 'blogs#show', as: 'blog'
    patch 'news/:title_for_slug', to: 'blogs#update'
    put 'news/:title_for_slug', to: 'blogs#update'
    delete 'news/:title_for_slug', to: 'blogs#destroy'

  #########################################
  #==press url for blog model
  #########################################
    get '/press', to: 'bligs#index', as: :bligs
    post 'press', to: 'bligs#create'
    get '/press/new', to: 'bligs#new', as: :new_blig
    get 'press/:title_for_slug/edit', to: 'bligs#edit', as: 'edit_blig'
    get 'press/:title_for_slug', to: 'bligs#show', as: 'blig'
    patch 'press/:title_for_slug', to: 'bligs#update'
    put 'press/:title_for_slug', to: 'bligs#update'
    delete 'press/:title_for_slug', to: 'bligs#destroy'

  match "/contacts"              =>        "contacts#create",              via: [:post]
  match "/applicants"            =>        "applicants#create",            via: [:post]
  
  get '/sitemap.xml', to: redirect("https://s3-us-west-2.amazonaws.com/gcg-group/sitemaps/sitemap.xml.gz", status: 301)

  match "*path", to: "home#catch_all", via: :all
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :applicants
  
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  
  before_save :title_url_it

  def title_url_it
    self.title_for_slug = name.downcase.squish.parameterize("-")
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :create, :destroy, :all_locations]

  def all_locations
    @locations = Location.order(:name)
  end

  def index
    @locations = Location.order(:name)
  end

  def new
    @location = Location.new
  end

  def edit
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to root_path, notice: "Location was created successfully"
    else
      render :new
    end
  end

  def update
    if @location.update(location_params)
      redirect_to root_path, notice: "Location was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @location.destroy
    redirect_to locations_url, notice: 'Location was successfully destroyed.'
  end

  private

  def set_location
    @location = Location.find_by(title_for_slug: params[:title_for_slug])
  end

  def location_params
    params.require(:location).permit(:name, :title_for_slug, :description, :gcg_ground, :gcg_events, :gcg_catering, :address, :latitude, :longitude, :title_for_maps, :phone, :fax, :specific_location, :iframe, image_attributes: [:id, :pic, :name])
  end

end

app/views/locations/_form.html.erb
<%= form_for(@location, :url => (@location.new_record? ? locations_url : location_path(@location.title_for_slug))) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.check_box :gcg_events %>
    <%= f.label :gcg_events %>
  </div>
  
  <div class="form-group">
    <%= f.check_box :gcg_catering %>
    <%= f.label :gcg_catering %>
  </div>
  
  <div class="form-group">
    <%= f.check_box :gcg_ground %>
    <%= f.label :gcg_ground %>
  </div>
  
  <div class="form-group">
    <%= f.submit class: "form-control btn btn-primary" %>
  </div>
<% end %>

app/views/locations/all_locations.html.erb
<% provide(:title, 'GCG Group | Locations') %>
<% content_for :head do%>
  <!-- <meta name="description" content="home description"> -->
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<div class="container mb40">
    <div class="row">
      <div class="col-sm-12">
        <div id="myid" data-mylocations="<%= @locations.to_json %>"></div>
        <div id="map"></div>
    </div>
  </div>
</div>

<div class="container">
  <table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Location Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
          <td><%= link_to 'Edit', edit_location_path(location.title_for_slug) %></td>
          <td><%= link_to 'Destroy', location_path(location.title_for_slug), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 
<br>

<% if current_user.try(:admin?) %>
  <%= link_to 'New Location', new_location_path, class: "btn btn-primary pull-right mb50" %>
<%  end %>
</div>

app/views/locations/edit.html.erb
<section class="hero-about mb30"></section>
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 mb30">
      <h2 class="mb30">Edit Location</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/locations/index.html.erb
<% provide(:title, 'GCG Group Locations in the Caribbean and Latin America | GCG Group') %>
<% content_for :head do%>
  <meta name="description" content="Discover our 24 locations throughout the Caribbean, Latin America, & Florida. Find branches for each of our catering, ground handling, & events divisions.">
  <!-- <meta name="keywords" content="about keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<section class="hero-locations" title="GCG Group locations throughout the Caribbean and Latin America"></section>

<!-- locations  -->
<!-- <section class="location">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3 class="mb90 text-center title-second">Our Locations</h3>
        <div class="map2">
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7864.340804889048!2d-80.29142555964783!3d26.03198117616144!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88d9a6254a0ad3ad%3A0xf69f72fe9da1776e!2s2525+Embassy+Dr+%2313%2C+Hollywood%2C+FL+33026!5e0!3m2!1sen!2sus!4v1494853568569" height="100%" width="100%" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
      </div>
    </div>
  </div>
</section> -->


<section class="location">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h3 class="mb90 text-center title-second">Our Locations <%= link_to "(Add/Edit location)", all_locations_path if current_user.try(:admin?)%></h3>
        <div class="map2" id="myid" data-mylocations="<%= @locations.to_json %>">

        <div id="map"></div>
      
      </div>


        </div>
      </div>
    </div>
  </div>
</section>




<section class="bg-light-grey">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h5 class="mb60 text-center">Send us a Message</h5>
        <div class="message">

          <%= form_for Contact.new, :html => { :id => "new_contact", :honeypot => true }, :url => {:controller => "contacts", :action => "create"} do |f| %>
          <div class="col-sm-4">
            <div class="form-group">
              <%= f.label :name, class: "sr-only" %>
              <%= f.text_field :name, class: "form-control", placeholder: "Full Name", required: true %>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="form-group">
              <%= f.label :email, class: "sr-only" %>
              <%= f.email_field :email, class: "form-control", placeholder: "Email", required: true %>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="form-group">
              <%= f.label :phone_number, class: "sr-only" %>
              <%= f.text_field :phone_number, class: "form-control", placeholder: "Phone", required: true %>
            </div>
          </div>
          <div class="col-sm-8">
            <div class="form-group">
              <%= f.label :message, class: "sr-only" %>
              <%= f.text_area :message, class: "form-control", rows: 3, placeholder: "Message", required: true %>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="form-group">
              <%= f.submit "Submit", class: "btn btn-default btn-xl" %>
            </div>
          </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/locations/new.html.erb
<section class="hero-about mb30"></section>
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 mb30">
      <h2 class="mb30">New Location</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>